global proc installMetaBox()
{
    string $scriptPath = `whatIs installMetaBox`;
    string $dirPath = `substring $scriptPath 25 (size($scriptPath))`;
    $dirPath = `dirname $dirPath`;
    string $pythonPath = $dirPath + "/Install.py";
    $pythonPath = substituteAllString($pythonPath, "\\", "/");
    python("import os, sys; sys.path.append(os.path.dirname(r'" + $pythonPath + "')); exec(open(r'" + $pythonPath + "', encoding='utf-8').read())");
}

installMetaBox();