# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Z:\CODES\vertexture\maya\ui\ziClosestUI.ui',
# licensing of 'Z:\CODES\vertexture\maya\ui\ziClosestUI.ui' applies.
#
# Created: Tue Jul  9 13:04:17 2024
#      by: pyside2-uic  running on PySide2 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ziClosestUI(object):
    def setupUi(self, ziClosestUI):
        ziClosestUI.setObjectName("ziClosestUI")
        ziClosestUI.resize(300, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ziClosestUI.sizePolicy().hasHeightForWidth())
        ziClosestUI.setSizePolicy(sizePolicy)
        ziClosestUI.setMinimumSize(QtCore.QSize(300, 400))
        ziClosestUI.setMaximumSize(QtCore.QSize(320, 550))
        ziClosestUI.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(ziClosestUI)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.ziCSpace = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ziCSpace.sizePolicy().hasHeightForWidth())
        self.ziCSpace.setSizePolicy(sizePolicy)
        self.ziCSpace.setMaximumSize(QtCore.QSize(16777215, 30))
        self.ziCSpace.setObjectName("ziCSpace")
        self.gridLayout.addWidget(self.ziCSpace, 0, 0, 1, 1)
        self.ziCVerbose = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ziCVerbose.sizePolicy().hasHeightForWidth())
        self.ziCVerbose.setSizePolicy(sizePolicy)
        self.ziCVerbose.setMaximumSize(QtCore.QSize(16777215, 30))
        self.ziCVerbose.setChecked(True)
        self.ziCVerbose.setObjectName("ziCVerbose")
        self.gridLayout.addWidget(self.ziCVerbose, 0, 1, 1, 1)
        self.ziCtextThres = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ziCtextThres.sizePolicy().hasHeightForWidth())
        self.ziCtextThres.setSizePolicy(sizePolicy)
        self.ziCtextThres.setMinimumSize(QtCore.QSize(0, 25))
        self.ziCtextThres.setMaximumSize(QtCore.QSize(16777215, 30))
        self.ziCtextThres.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ziCtextThres.setObjectName("ziCtextThres")
        self.gridLayout.addWidget(self.ziCtextThres, 0, 3, 1, 1)
        self.ziCThres = QtWidgets.QLineEdit(self.centralwidget)
        self.ziCThres.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ziCThres.sizePolicy().hasHeightForWidth())
        self.ziCThres.setSizePolicy(sizePolicy)
        self.ziCThres.setMaximumSize(QtCore.QSize(40, 30))
        self.ziCThres.setCursor(QtCore.Qt.IBeamCursor)
        self.ziCThres.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.ziCThres.setMaxLength(5)
        self.ziCThres.setFrame(True)
        self.ziCThres.setAlignment(QtCore.Qt.AlignCenter)
        self.ziCThres.setReadOnly(False)
        self.ziCThres.setObjectName("ziCThres")
        self.gridLayout.addWidget(self.ziCThres, 0, 4, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(9, -1, -1, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.highName = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.highName.sizePolicy().hasHeightForWidth())
        self.highName.setSizePolicy(sizePolicy)
        self.highName.setText("")
        self.highName.setAlignment(QtCore.Qt.AlignCenter)
        self.highName.setObjectName("highName")
        self.gridLayout_4.addWidget(self.highName, 3, 0, 1, 1)
        self.lowName = QtWidgets.QLabel(self.frame)
        self.lowName.setText("")
        self.lowName.setAlignment(QtCore.Qt.AlignCenter)
        self.lowName.setObjectName("lowName")
        self.gridLayout_4.addWidget(self.lowName, 3, 1, 1, 1)
        self.ziCHigBtn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ziCHigBtn.sizePolicy().hasHeightForWidth())
        self.ziCHigBtn.setSizePolicy(sizePolicy)
        self.ziCHigBtn.setMinimumSize(QtCore.QSize(100, 100))
        self.ziCHigBtn.setMaximumSize(QtCore.QSize(120, 120))
        self.ziCHigBtn.setBaseSize(QtCore.QSize(0, 0))
        self.ziCHigBtn.setStyleSheet("")
        self.ziCHigBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/skin/neon/rabbitHigh.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ziCHigBtn.setIcon(icon)
        self.ziCHigBtn.setIconSize(QtCore.QSize(100, 100))
        self.ziCHigBtn.setFlat(False)
        self.ziCHigBtn.setObjectName("ziCHigBtn")
        self.gridLayout_4.addWidget(self.ziCHigBtn, 2, 0, 1, 1)
        self.ziCLowBtn = QtWidgets.QPushButton(self.frame)
        self.ziCLowBtn.setMinimumSize(QtCore.QSize(130, 100))
        self.ziCLowBtn.setMaximumSize(QtCore.QSize(120, 120))
        self.ziCLowBtn.setBaseSize(QtCore.QSize(0, 0))
        self.ziCLowBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/logo/skin/neon/rabbitLow.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ziCLowBtn.setIcon(icon1)
        self.ziCLowBtn.setIconSize(QtCore.QSize(100, 100))
        self.ziCLowBtn.setFlat(False)
        self.ziCLowBtn.setObjectName("ziCLowBtn")
        self.gridLayout_4.addWidget(self.ziCLowBtn, 2, 1, 1, 1)
        self.referencebtn = QtWidgets.QPushButton(self.frame)
        self.referencebtn.setMaximumSize(QtCore.QSize(120, 16777215))
        self.referencebtn.setObjectName("referencebtn")
        self.gridLayout_4.addWidget(self.referencebtn, 0, 0, 1, 1)
        self.shaderbtn = QtWidgets.QPushButton(self.frame)
        self.shaderbtn.setMaximumSize(QtCore.QSize(9999, 16777215))
        self.shaderbtn.setObjectName("shaderbtn")
        self.gridLayout_4.addWidget(self.shaderbtn, 0, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setMaximumSize(QtCore.QSize(120, 16777215))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 1, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_4.addWidget(self.line_2, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_4)
        self.verticalLayout_2.addWidget(self.frame)
        self.ziCFrame = QtWidgets.QFrame(self.centralwidget)
        self.ziCFrame.setEnabled(True)
        self.ziCFrame.setAutoFillBackground(False)
        self.ziCFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ziCFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ziCFrame.setLineWidth(9)
        self.ziCFrame.setMidLineWidth(9)
        self.ziCFrame.setObjectName("ziCFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.ziCFrame)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ziStat = QtWidgets.QLabel(self.ziCFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ziStat.sizePolicy().hasHeightForWidth())
        self.ziStat.setSizePolicy(sizePolicy)
        self.ziStat.setMinimumSize(QtCore.QSize(0, 0))
        self.ziStat.setMaximumSize(QtCore.QSize(16777215, 360))
        self.ziStat.setCursor(QtCore.Qt.IBeamCursor)
        self.ziStat.setTextFormat(QtCore.Qt.RichText)
        self.ziStat.setScaledContents(False)
        self.ziStat.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ziStat.setWordWrap(False)
        self.ziStat.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.ziStat.setObjectName("ziStat")
        self.verticalLayout_4.addWidget(self.ziStat)
        self.label = QtWidgets.QLabel(self.ziCFrame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.widget = QtWidgets.QWidget(self.ziCFrame)
        self.widget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ziCFrameMesh = QtWidgets.QFrame(self.widget)
        self.ziCFrameMesh.setEnabled(True)
        self.ziCFrameMesh.setMinimumSize(QtCore.QSize(0, 25))
        self.ziCFrameMesh.setMaximumSize(QtCore.QSize(16777215, 25))
        self.ziCFrameMesh.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ziCFrameMesh.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ziCFrameMesh.setObjectName("ziCFrameMesh")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.ziCFrameMesh)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ziCFaceMode_btn = QtWidgets.QPushButton(self.ziCFrameMesh)
        self.ziCFaceMode_btn.setEnabled(True)
        self.ziCFaceMode_btn.setMinimumSize(QtCore.QSize(0, 23))
        self.ziCFaceMode_btn.setCursor(QtCore.Qt.ArrowCursor)
        self.ziCFaceMode_btn.setCheckable(True)
        self.ziCFaceMode_btn.setChecked(True)
        self.ziCFaceMode_btn.setAutoExclusive(True)
        self.ziCFaceMode_btn.setDefault(False)
        self.ziCFaceMode_btn.setFlat(False)
        self.ziCFaceMode_btn.setObjectName("ziCFaceMode_btn")
        self.horizontalLayout_4.addWidget(self.ziCFaceMode_btn)
        self.ziCVertexMode_btn = QtWidgets.QPushButton(self.ziCFrameMesh)
        self.ziCVertexMode_btn.setEnabled(True)
        self.ziCVertexMode_btn.setMinimumSize(QtCore.QSize(0, 23))
        self.ziCVertexMode_btn.setCursor(QtCore.Qt.ArrowCursor)
        self.ziCVertexMode_btn.setCheckable(True)
        self.ziCVertexMode_btn.setChecked(False)
        self.ziCVertexMode_btn.setAutoExclusive(True)
        self.ziCVertexMode_btn.setObjectName("ziCVertexMode_btn")
        self.horizontalLayout_4.addWidget(self.ziCVertexMode_btn)
        self.ziCOrderxMode_btn = QtWidgets.QPushButton(self.ziCFrameMesh)
        self.ziCOrderxMode_btn.setEnabled(True)
        self.ziCOrderxMode_btn.setMinimumSize(QtCore.QSize(0, 23))
        self.ziCOrderxMode_btn.setCursor(QtCore.Qt.ArrowCursor)
        self.ziCOrderxMode_btn.setCheckable(True)
        self.ziCOrderxMode_btn.setChecked(False)
        self.ziCOrderxMode_btn.setAutoExclusive(True)
        self.ziCOrderxMode_btn.setObjectName("ziCOrderxMode_btn")
        self.horizontalLayout_4.addWidget(self.ziCOrderxMode_btn)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.ziCFrameMesh)
        self.ziCFrameCurve = QtWidgets.QFrame(self.widget)
        self.ziCFrameCurve.setEnabled(True)
        self.ziCFrameCurve.setMinimumSize(QtCore.QSize(0, 25))
        self.ziCFrameCurve.setMaximumSize(QtCore.QSize(16777215, 25))
        self.ziCFrameCurve.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ziCFrameCurve.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ziCFrameCurve.setObjectName("ziCFrameCurve")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.ziCFrameCurve)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.curve = QtWidgets.QHBoxLayout()
        self.curve.setObjectName("curve")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.curve.addItem(spacerItem)
        self.constant_radio = QtWidgets.QRadioButton(self.ziCFrameCurve)
        self.constant_radio.setEnabled(True)
        self.constant_radio.setChecked(True)
        self.constant_radio.setAutoExclusive(True)
        self.constant_radio.setObjectName("constant_radio")
        self.curve.addWidget(self.constant_radio)
        self.even_radio = QtWidgets.QRadioButton(self.ziCFrameCurve)
        self.even_radio.setEnabled(True)
        self.even_radio.setChecked(False)
        self.even_radio.setAutoExclusive(True)
        self.even_radio.setObjectName("even_radio")
        self.curve.addWidget(self.even_radio)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.curve.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.curve, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.ziCFrameCurve)
        self.verticalLayout_4.addWidget(self.widget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ziClog = QtWidgets.QLineEdit(self.ziCFrame)
        self.ziClog.setEnabled(True)
        self.ziClog.setMinimumSize(QtCore.QSize(0, 22))
        self.ziClog.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ziClog.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.ziClog.setAcceptDrops(False)
        self.ziClog.setAccessibleName("")
        self.ziClog.setAccessibleDescription("")
        self.ziClog.setFrame(False)
        self.ziClog.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.ziClog.setCursorPosition(18)
        self.ziClog.setAlignment(QtCore.Qt.AlignCenter)
        self.ziClog.setReadOnly(True)
        self.ziClog.setObjectName("ziClog")
        self.verticalLayout.addWidget(self.ziClog)
        self.ziCProgress = QtWidgets.QProgressBar(self.ziCFrame)
        self.ziCProgress.setEnabled(True)
        self.ziCProgress.setMinimumSize(QtCore.QSize(0, 18))
        self.ziCProgress.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ziCProgress.setFont(font)
        self.ziCProgress.setProperty("value", 0)
        self.ziCProgress.setTextVisible(True)
        self.ziCProgress.setInvertedAppearance(False)
        self.ziCProgress.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.ziCProgress.setObjectName("ziCProgress")
        self.verticalLayout.addWidget(self.ziCProgress)
        self.line_4 = QtWidgets.QFrame(self.ziCFrame)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ziCTransfer = QtWidgets.QPushButton(self.ziCFrame)
        self.ziCTransfer.setEnabled(True)
        self.ziCTransfer.setMinimumSize(QtCore.QSize(0, 20))
        self.ziCTransfer.setObjectName("ziCTransfer")
        self.horizontalLayout.addWidget(self.ziCTransfer)
        self.ziCConstraint = QtWidgets.QPushButton(self.ziCFrame)
        self.ziCConstraint.setEnabled(True)
        self.ziCConstraint.setMinimumSize(QtCore.QSize(0, 20))
        self.ziCConstraint.setCheckable(True)
        self.ziCConstraint.setObjectName("ziCConstraint")
        self.horizontalLayout.addWidget(self.ziCConstraint)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2.addWidget(self.ziCFrame)
        self.ziStuzzi = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ziStuzzi.sizePolicy().hasHeightForWidth())
        self.ziStuzzi.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.ziStuzzi.setFont(font)
        self.ziStuzzi.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ziStuzzi.setObjectName("ziStuzzi")
        self.verticalLayout_2.addWidget(self.ziStuzzi)
        ziClosestUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(ziClosestUI)
        QtCore.QMetaObject.connectSlotsByName(ziClosestUI)

    def retranslateUi(self, ziClosestUI):
        ziClosestUI.setWindowTitle(QtWidgets.QApplication.translate("ziClosestUI", "ziClosestPoint", None, -1))
        self.ziCSpace.setText(QtWidgets.QApplication.translate("ziClosestUI", "Local Space", None, -1))
        self.ziCVerbose.setText(QtWidgets.QApplication.translate("ziClosestUI", "Verbose", None, -1))
        self.ziCtextThres.setText(QtWidgets.QApplication.translate("ziClosestUI", "Tolerance", None, -1))
        self.ziCThres.setText(QtWidgets.QApplication.translate("ziClosestUI", "0.01", None, -1))
        self.referencebtn.setText(QtWidgets.QApplication.translate("ziClosestUI", "Reference", None, -1))
        self.shaderbtn.setText(QtWidgets.QApplication.translate("ziClosestUI", "Retopo Shader", None, -1))
        self.ziStat.setText(QtWidgets.QApplication.translate("ziClosestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt; color:#aaaaaa;\">Source as: ...</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt; color:#aaaaaa;\">    Display type: ...</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt; color:#aaaaaa;\">    PolyCount: ...</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt; color:#aaaaaa;\">Target as: ...</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt; color:#aaaaaa;\">    Components: ...</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7pt; color:#aaaaaa;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt; color:#aaaaaa;\">Execution time: ...</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p></body></html>", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("ziClosestUI", "MODE", None, -1))
        self.ziCFaceMode_btn.setText(QtWidgets.QApplication.translate("ziClosestUI", "FACE", None, -1))
        self.ziCVertexMode_btn.setText(QtWidgets.QApplication.translate("ziClosestUI", "VERTEX", None, -1))
        self.ziCOrderxMode_btn.setText(QtWidgets.QApplication.translate("ziClosestUI", "ORDER", None, -1))
        self.constant_radio.setText(QtWidgets.QApplication.translate("ziClosestUI", "Constant", None, -1))
        self.even_radio.setText(QtWidgets.QApplication.translate("ziClosestUI", "Even", None, -1))
        self.ziClog.setText(QtWidgets.QApplication.translate("ziClosestUI", "Please Add An Item", None, -1))
        self.ziCTransfer.setText(QtWidgets.QApplication.translate("ziClosestUI", "Transfer", None, -1))
        self.ziCConstraint.setText(QtWidgets.QApplication.translate("ziClosestUI", "Connect", None, -1))
        self.ziStuzzi.setText(QtWidgets.QApplication.translate("ziClosestUI", "www.vertexture.org", None, -1))

from . import ziRessources_rc

# -- Vtx python version 3
