# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Z:\CODES\vertexture\maya\ui\ziRailUI.ui',
# licensing of 'Z:\CODES\vertexture\maya\ui\ziRailUI.ui' applies.
#
# Created: Tue Jul  9 13:04:17 2024
#      by: pyside2-uic  running on PySide2 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ziRailWindow(object):
    def setupUi(self, ziRailWindow):
        ziRailWindow.setObjectName("ziRailWindow")
        ziRailWindow.resize(316, 719)
        ziRailWindow.setMinimumSize(QtCore.QSize(10, 10))
        ziRailWindow.setMaximumSize(QtCore.QSize(999, 16777215))
        ziRailWindow.setStyleSheet("")
        ziRailWindow.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        ziRailWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(ziRailWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("QGroupBox:hover{\n"
"color: rgb(0, 255, 0);\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"\n"
" border-style: solid;\n"
"  height: 21px;\n"
" border-width:1px;\n"
" border-radius:2px;\n"
"\n"
"\n"
" border-color: #666666;\n"
" background-color: #5d5d5d;\n"
" color: #DDDDDD;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" border-color: #999999;\n"
" color: #FFFFFF;\n"
"}\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setEnabled(True)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setEnabled(True)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 314, 602))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(16777215, 9999999))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(4)
        self.horizontalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pickSrcBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pickSrcBtn.setMinimumSize(QtCore.QSize(0, 30))
        self.pickSrcBtn.setIconSize(QtCore.QSize(24, 24))
        self.pickSrcBtn.setObjectName("pickSrcBtn")
        self.horizontalLayout_7.addWidget(self.pickSrcBtn)
        self.refBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.refBox.setObjectName("refBox")
        self.horizontalLayout_7.addWidget(self.refBox)
        self.horizontalLayout_7.setStretch(0, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.line_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.box1 = ziCollapse(self.scrollAreaWidgetContents)
        self.box1.setAutoFillBackground(True)
        self.box1.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.box1.setProperty("flat", True)
        self.box1.setObjectName("box1")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.box1)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_8 = QtWidgets.QFrame(self.box1)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_5.setSpacing(1)
        self.gridLayout_5.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lockedPinchChk = QtWidgets.QCheckBox(self.frame_8)
        self.lockedPinchChk.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lockedPinchChk.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lockedPinchChk.setChecked(True)
        self.lockedPinchChk.setObjectName("lockedPinchChk")
        self.horizontalLayout_8.addWidget(self.lockedPinchChk)
        self.pinchSlid = QtWidgets.QSlider(self.frame_8)
        self.pinchSlid.setMinimumSize(QtCore.QSize(0, 0))
        self.pinchSlid.setStyleSheet("\"\"")
        self.pinchSlid.setMinimum(-100)
        self.pinchSlid.setMaximum(100)
        self.pinchSlid.setSingleStep(1)
        self.pinchSlid.setProperty("value", 0)
        self.pinchSlid.setOrientation(QtCore.Qt.Horizontal)
        self.pinchSlid.setInvertedAppearance(False)
        self.pinchSlid.setInvertedControls(False)
        self.pinchSlid.setTickInterval(10)
        self.pinchSlid.setObjectName("pinchSlid")
        self.horizontalLayout_8.addWidget(self.pinchSlid)
        self.slidBtn = QtWidgets.QPushButton(self.frame_8)
        self.slidBtn.setMinimumSize(QtCore.QSize(80, 0))
        self.slidBtn.setMaximumSize(QtCore.QSize(60, 16777215))
        self.slidBtn.setStyleSheet("\"\"")
        self.slidBtn.setObjectName("slidBtn")
        self.horizontalLayout_8.addWidget(self.slidBtn)
        self.horizontalLayout_8.setStretch(1, 1)
        self.gridLayout_5.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setHorizontalSpacing(2)
        self.gridLayout_9.setVerticalSpacing(4)
        self.gridLayout_9.setObjectName("gridLayout_9")
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem, 1, 0, 1, 1)
        self.Vspin = QtWidgets.QDoubleSpinBox(self.frame_8)
        self.Vspin.setMinimumSize(QtCore.QSize(0, 27))
        self.Vspin.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Vspin.setFont(font)
        self.Vspin.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Vspin.setFrame(False)
        self.Vspin.setAlignment(QtCore.Qt.AlignCenter)
        self.Vspin.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.Vspin.setDecimals(0)
        self.Vspin.setMinimum(1.0)
        self.Vspin.setProperty("value", 10.0)
        self.Vspin.setObjectName("Vspin")
        self.gridLayout_9.addWidget(self.Vspin, 1, 7, 1, 1)
        self.upVBtn = QtWidgets.QPushButton(self.frame_8)
        self.upVBtn.setMinimumSize(QtCore.QSize(20, 20))
        self.upVBtn.setMaximumSize(QtCore.QSize(30, 30))
        self.upVBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/generic/skin/generic/in.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upVBtn.setIcon(icon)
        self.upVBtn.setIconSize(QtCore.QSize(50, 50))
        self.upVBtn.setFlat(True)
        self.upVBtn.setObjectName("upVBtn")
        self.gridLayout_9.addWidget(self.upVBtn, 1, 5, 1, 1)
        self.dnVBtn = QtWidgets.QPushButton(self.frame_8)
        self.dnVBtn.setMinimumSize(QtCore.QSize(20, 20))
        self.dnVBtn.setMaximumSize(QtCore.QSize(30, 30))
        self.dnVBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/generic/skin/generic/out.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dnVBtn.setIcon(icon1)
        self.dnVBtn.setIconSize(QtCore.QSize(50, 50))
        self.dnVBtn.setFlat(True)
        self.dnVBtn.setObjectName("dnVBtn")
        self.gridLayout_9.addWidget(self.dnVBtn, 1, 8, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem1, 1, 10, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem2, 0, 10, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem3, 0, 0, 1, 1)
        self.Uspin = QtWidgets.QDoubleSpinBox(self.frame_8)
        self.Uspin.setMinimumSize(QtCore.QSize(0, 27))
        self.Uspin.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Uspin.setFont(font)
        self.Uspin.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Uspin.setFrame(False)
        self.Uspin.setAlignment(QtCore.Qt.AlignCenter)
        self.Uspin.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.Uspin.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.Uspin.setDecimals(0)
        self.Uspin.setMinimum(1.0)
        self.Uspin.setMaximum(50.0)
        self.Uspin.setProperty("value", 10.0)
        self.Uspin.setObjectName("Uspin")
        self.gridLayout_9.addWidget(self.Uspin, 0, 7, 1, 1)
        self.upUBtn = QtWidgets.QPushButton(self.frame_8)
        self.upUBtn.setMinimumSize(QtCore.QSize(20, 20))
        self.upUBtn.setMaximumSize(QtCore.QSize(30, 30))
        self.upUBtn.setText("")
        self.upUBtn.setIcon(icon)
        self.upUBtn.setIconSize(QtCore.QSize(64, 64))
        self.upUBtn.setFlat(True)
        self.upUBtn.setObjectName("upUBtn")
        self.gridLayout_9.addWidget(self.upUBtn, 0, 5, 1, 1)
        self.dnUBtn = QtWidgets.QPushButton(self.frame_8)
        self.dnUBtn.setMinimumSize(QtCore.QSize(20, 20))
        self.dnUBtn.setMaximumSize(QtCore.QSize(30, 30))
        self.dnUBtn.setText("")
        self.dnUBtn.setIcon(icon1)
        self.dnUBtn.setIconSize(QtCore.QSize(50, 50))
        self.dnUBtn.setFlat(True)
        self.dnUBtn.setObjectName("dnUBtn")
        self.gridLayout_9.addWidget(self.dnUBtn, 0, 8, 1, 1)
        self.uLabUp = QtWidgets.QLabel(self.frame_8)
        self.uLabUp.setObjectName("uLabUp")
        self.gridLayout_9.addWidget(self.uLabUp, 0, 3, 1, 1)
        self.vLabUp = QtWidgets.QLabel(self.frame_8)
        self.vLabUp.setObjectName("vLabUp")
        self.gridLayout_9.addWidget(self.vLabUp, 1, 3, 1, 1)
        self.uLabDn = QtWidgets.QLabel(self.frame_8)
        self.uLabDn.setObjectName("uLabDn")
        self.gridLayout_9.addWidget(self.uLabDn, 0, 9, 1, 1)
        self.vLabDn = QtWidgets.QLabel(self.frame_8)
        self.vLabDn.setObjectName("vLabDn")
        self.gridLayout_9.addWidget(self.vLabDn, 1, 9, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.distanceSpin = QtWidgets.QDoubleSpinBox(self.frame_8)
        self.distanceSpin.setMinimumSize(QtCore.QSize(0, 18))
        self.distanceSpin.setMaximumSize(QtCore.QSize(50, 16777215))
        self.distanceSpin.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.distanceSpin.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.distanceSpin.setWrapping(True)
        self.distanceSpin.setFrame(False)
        self.distanceSpin.setAlignment(QtCore.Qt.AlignCenter)
        self.distanceSpin.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.distanceSpin.setAccelerated(True)
        self.distanceSpin.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.distanceSpin.setProperty("showGroupSeparator", False)
        self.distanceSpin.setDecimals(1)
        self.distanceSpin.setMinimum(0.0)
        self.distanceSpin.setMaximum(9000.0)
        self.distanceSpin.setSingleStep(0.1)
        self.distanceSpin.setProperty("value", 0.0)
        self.distanceSpin.setObjectName("distanceSpin")
        self.horizontalLayout_4.addWidget(self.distanceSpin)
        self.projSlid = QtWidgets.QSlider(self.frame_8)
        self.projSlid.setMinimumSize(QtCore.QSize(0, 0))
        self.projSlid.setMinimum(0)
        self.projSlid.setMaximum(100)
        self.projSlid.setOrientation(QtCore.Qt.Horizontal)
        self.projSlid.setInvertedAppearance(False)
        self.projSlid.setInvertedControls(False)
        self.projSlid.setTickInterval(10)
        self.projSlid.setObjectName("projSlid")
        self.horizontalLayout_4.addWidget(self.projSlid)
        self.displayProjBtn = QtWidgets.QPushButton(self.frame_8)
        self.displayProjBtn.setMinimumSize(QtCore.QSize(80, 0))
        self.displayProjBtn.setCheckable(True)
        self.displayProjBtn.setObjectName("displayProjBtn")
        self.horizontalLayout_4.addWidget(self.displayProjBtn)
        self.horizontalLayout_4.setStretch(1, 1)
        self.gridLayout_5.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.bridgeSpin = QtWidgets.QSpinBox(self.frame_8)
        self.bridgeSpin.setMinimumSize(QtCore.QSize(50, 18))
        self.bridgeSpin.setMaximumSize(QtCore.QSize(60, 16777215))
        self.bridgeSpin.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.bridgeSpin.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bridgeSpin.setWrapping(True)
        self.bridgeSpin.setFrame(False)
        self.bridgeSpin.setAlignment(QtCore.Qt.AlignCenter)
        self.bridgeSpin.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.bridgeSpin.setAccelerated(True)
        self.bridgeSpin.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.bridgeSpin.setProperty("showGroupSeparator", False)
        self.bridgeSpin.setSuffix("")
        self.bridgeSpin.setMinimum(0)
        self.bridgeSpin.setMaximum(50)
        self.bridgeSpin.setObjectName("bridgeSpin")
        self.horizontalLayout_6.addWidget(self.bridgeSpin)
        self.bridg_lab = QtWidgets.QLabel(self.frame_8)
        self.bridg_lab.setMaximumSize(QtCore.QSize(60, 16777215))
        self.bridg_lab.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.bridg_lab.setObjectName("bridg_lab")
        self.horizontalLayout_6.addWidget(self.bridg_lab)
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.reversBridgBtn = QtWidgets.QPushButton(self.frame_8)
        self.reversBridgBtn.setMinimumSize(QtCore.QSize(80, 0))
        self.reversBridgBtn.setMaximumSize(QtCore.QSize(80, 16777215))
        self.reversBridgBtn.setObjectName("reversBridgBtn")
        self.horizontalLayout_6.addWidget(self.reversBridgBtn)
        self.horizontalLayout_6.setStretch(1, 1)
        self.gridLayout_5.addLayout(self.horizontalLayout_6, 3, 0, 1, 1)
        self.verticalLayout_11.addWidget(self.frame_8)
        self.verticalLayout.addWidget(self.box1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(1)
        self.horizontalLayout_5.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tweakBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.tweakBtn.setMinimumSize(QtCore.QSize(0, 22))
        self.tweakBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tweakBtn.setAutoFillBackground(False)
        self.tweakBtn.setCheckable(True)
        self.tweakBtn.setAutoDefault(False)
        self.tweakBtn.setDefault(False)
        self.tweakBtn.setFlat(False)
        self.tweakBtn.setObjectName("tweakBtn")
        self.verticalLayout_3.addWidget(self.tweakBtn)
        self.line_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_3.addWidget(self.line_7)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.box2 = ziCollapse(self.scrollAreaWidgetContents)
        self.box2.setMaximumSize(QtCore.QSize(16777215, 120))
        self.box2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.box2.setProperty("flat", True)
        self.box2.setObjectName("box2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.box2)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.box2)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 110))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLay_9 = QtWidgets.QVBoxLayout()
        self.verticalLay_9.setSpacing(0)
        self.verticalLay_9.setObjectName("verticalLay_9")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.viewportBtn = QtWidgets.QPushButton(self.frame_3)
        self.viewportBtn.setObjectName("viewportBtn")
        self.horizontalLayout.addWidget(self.viewportBtn)
        self.shaderApplyBtn = QtWidgets.QPushButton(self.frame_3)
        self.shaderApplyBtn.setCheckable(True)
        self.shaderApplyBtn.setObjectName("shaderApplyBtn")
        self.horizontalLayout.addWidget(self.shaderApplyBtn)
        self.verticalLay_9.addLayout(self.horizontalLayout)
        self.colorLayoutTop = QtWidgets.QHBoxLayout()
        self.colorLayoutTop.setSpacing(0)
        self.colorLayoutTop.setObjectName("colorLayoutTop")
        self.verticalLay_9.addLayout(self.colorLayoutTop)
        self.colorLayoutBot = QtWidgets.QHBoxLayout()
        self.colorLayoutBot.setSpacing(0)
        self.colorLayoutBot.setObjectName("colorLayoutBot")
        self.verticalLay_9.addLayout(self.colorLayoutBot)
        self.verticalLay_9.setStretch(1, 1)
        self.verticalLay_9.setStretch(2, 1)
        self.verticalLayout_6.addLayout(self.verticalLay_9)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.box2)
        self.line_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout.addWidget(self.line_6)
        self.box3 = ziCollapse(self.scrollAreaWidgetContents)
        self.box3.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.box3.setProperty("flat", True)
        self.box3.setObjectName("box3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.box3)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.box3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_2.setHorizontalSpacing(2)
        self.gridLayout_2.setVerticalSpacing(1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_3.setHorizontalSpacing(3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.line_3 = QtWidgets.QFrame(self.frame_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_3.addWidget(self.line_3, 2, 0, 1, 3)
        self.radiusSlid = QtWidgets.QSlider(self.frame_2)
        self.radiusSlid.setEnabled(True)
        self.radiusSlid.setMinimumSize(QtCore.QSize(0, 18))
        self.radiusSlid.setStyleSheet("\"\"")
        self.radiusSlid.setProperty("value", 50)
        self.radiusSlid.setOrientation(QtCore.Qt.Horizontal)
        self.radiusSlid.setObjectName("radiusSlid")
        self.gridLayout_3.addWidget(self.radiusSlid, 3, 1, 1, 2)
        self.moverad_lab = QtWidgets.QLabel(self.frame_2)
        self.moverad_lab.setMinimumSize(QtCore.QSize(50, 22))
        self.moverad_lab.setObjectName("moverad_lab")
        self.gridLayout_3.addWidget(self.moverad_lab, 4, 0, 1, 1)
        self.relaxrad_lab = QtWidgets.QLabel(self.frame_2)
        self.relaxrad_lab.setMinimumSize(QtCore.QSize(50, 22))
        self.relaxrad_lab.setObjectName("relaxrad_lab")
        self.gridLayout_3.addWidget(self.relaxrad_lab, 3, 0, 1, 1)
        self.forceSlid = QtWidgets.QSlider(self.frame_2)
        self.forceSlid.setEnabled(True)
        self.forceSlid.setMinimumSize(QtCore.QSize(0, 18))
        self.forceSlid.setMinimum(0)
        self.forceSlid.setSingleStep(1)
        self.forceSlid.setProperty("value", 50)
        self.forceSlid.setOrientation(QtCore.Qt.Horizontal)
        self.forceSlid.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.forceSlid.setObjectName("forceSlid")
        self.gridLayout_3.addWidget(self.forceSlid, 1, 1, 1, 2)
        self.relaxint_lab = QtWidgets.QLabel(self.frame_2)
        self.relaxint_lab.setMinimumSize(QtCore.QSize(50, 22))
        self.relaxint_lab.setObjectName("relaxint_lab")
        self.gridLayout_3.addWidget(self.relaxint_lab, 1, 0, 1, 1)
        self.tweakRadSlid = QtWidgets.QSlider(self.frame_2)
        self.tweakRadSlid.setEnabled(True)
        self.tweakRadSlid.setMinimumSize(QtCore.QSize(0, 18))
        self.tweakRadSlid.setStyleSheet("\"\"")
        self.tweakRadSlid.setMaximum(200)
        self.tweakRadSlid.setProperty("value", 50)
        self.tweakRadSlid.setOrientation(QtCore.Qt.Horizontal)
        self.tweakRadSlid.setObjectName("tweakRadSlid")
        self.gridLayout_3.addWidget(self.tweakRadSlid, 4, 1, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout_3, 2, 1, 1, 1)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.relaxBrBtn = QtWidgets.QPushButton(self.frame_2)
        self.relaxBrBtn.setMinimumSize(QtCore.QSize(0, 23))
        self.relaxBrBtn.setBaseSize(QtCore.QSize(0, 23))
        self.relaxBrBtn.setCheckable(False)
        self.relaxBrBtn.setObjectName("relaxBrBtn")
        self.horizontalLayout_9.addWidget(self.relaxBrBtn)
        self.moveBtn = QtWidgets.QPushButton(self.frame_2)
        self.moveBtn.setMinimumSize(QtCore.QSize(0, 23))
        self.moveBtn.setBaseSize(QtCore.QSize(0, 23))
        self.moveBtn.setObjectName("moveBtn")
        self.horizontalLayout_9.addWidget(self.moveBtn)
        self.freezeBBtn = QtWidgets.QPushButton(self.frame_2)
        self.freezeBBtn.setMinimumSize(QtCore.QSize(0, 23))
        self.freezeBBtn.setBaseSize(QtCore.QSize(0, 23))
        self.freezeBBtn.setCheckable(False)
        self.freezeBBtn.setObjectName("freezeBBtn")
        self.horizontalLayout_9.addWidget(self.freezeBBtn)
        self.verticalLayout_13.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.backfBtn = QtWidgets.QPushButton(self.frame_2)
        self.backfBtn.setMinimumSize(QtCore.QSize(0, 23))
        self.backfBtn.setBaseSize(QtCore.QSize(0, 23))
        self.backfBtn.setCheckable(True)
        self.backfBtn.setObjectName("backfBtn")
        self.horizontalLayout_11.addWidget(self.backfBtn)
        self.freezeBtn = QtWidgets.QPushButton(self.frame_2)
        self.freezeBtn.setMinimumSize(QtCore.QSize(0, 23))
        self.freezeBtn.setBaseSize(QtCore.QSize(0, 23))
        self.freezeBtn.setCheckable(True)
        self.freezeBtn.setObjectName("freezeBtn")
        self.horizontalLayout_11.addWidget(self.freezeBtn)
        self.verticalLayout_13.addLayout(self.horizontalLayout_11)
        self.gridLayout_2.addLayout(self.verticalLayout_13, 0, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.frame_2)
        self.line = QtWidgets.QFrame(self.box3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_5.addWidget(self.line)
        self.verticalLayout.addWidget(self.box3)
        self.line_8 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout.addWidget(self.line_8)
        self.box4 = ziCollapse(self.scrollAreaWidgetContents)
        self.box4.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.box4.setProperty("flat", True)
        self.box4.setObjectName("box4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.box4)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_4 = QtWidgets.QFrame(self.box4)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setContentsMargins(0, 0, 1, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.ziRailLaunchBtn = QtWidgets.QPushButton(self.frame_4)
        self.ziRailLaunchBtn.setMinimumSize(QtCore.QSize(0, 50))
        self.ziRailLaunchBtn.setStyleSheet(".QPushButton{ \n"
" border-style: solid;\n"
" border-width:1px;\n"
" border-radius:3px;\n"
" border-color: #333333;\n"
" }\n"
"\n"
"QPushButton:hover{\n"
" border-color: #AAAAAA;\n"
" color: #AAAAAA;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
" border-color: rgb(126,131,90);\n"
" border-width:2px;\n"
" color: rgb(126,131,90);\n"
"}\n"
"\n"
"\n"
"")
        self.ziRailLaunchBtn.setIconSize(QtCore.QSize(24, 24))
        self.ziRailLaunchBtn.setCheckable(True)
        self.ziRailLaunchBtn.setObjectName("ziRailLaunchBtn")
        self.verticalLayout_8.addWidget(self.ziRailLaunchBtn)
        self.quadBtn = QtWidgets.QPushButton(self.frame_4)
        self.quadBtn.setCheckable(False)
        self.quadBtn.setObjectName("quadBtn")
        self.verticalLayout_8.addWidget(self.quadBtn)
        self.shadeFrame = QtWidgets.QFrame(self.frame_4)
        self.shadeFrame.setStyleSheet("QPushButton{  \n"
" border-style: solid;\n"
" border-width:1px;\n"
" border-radius:8px;\n"
" border-color: #333333;\n"
" color: #333333;\n"
" background-color: rgba(126,131,90,0);\n"
"/*background-color: #444444;*/\n"
"\n"
"text-align:bottom;\n"
"vertical-align: text-bottom;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" border-color: #AAAAAA;\n"
" color: #AAAAAA;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
" border-color: rgba(126,131,90,255);\n"
" color: rgba(126,131,90,255);\n"
"}")
        self.shadeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.shadeFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.shadeFrame.setObjectName("shadeFrame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.shadeFrame)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.strokeBtn = QtWidgets.QPushButton(self.shadeFrame)
        self.strokeBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.strokeBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.strokeBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/vertexture/skin/vertexture/misc/draw.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.strokeBtn.setIcon(icon2)
        self.strokeBtn.setIconSize(QtCore.QSize(50, 50))
        self.strokeBtn.setCheckable(True)
        self.strokeBtn.setChecked(True)
        self.strokeBtn.setObjectName("strokeBtn")
        self.horizontalLayout_3.addWidget(self.strokeBtn)
        self.lineBtn = QtWidgets.QPushButton(self.shadeFrame)
        self.lineBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.lineBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/vertexture/skin/vertexture/misc/line.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lineBtn.setIcon(icon3)
        self.lineBtn.setIconSize(QtCore.QSize(50, 50))
        self.lineBtn.setCheckable(True)
        self.lineBtn.setObjectName("lineBtn")
        self.horizontalLayout_3.addWidget(self.lineBtn)
        self.squareBtn = QtWidgets.QPushButton(self.shadeFrame)
        self.squareBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.squareBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/vertexture/skin/vertexture/misc/square.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.squareBtn.setIcon(icon4)
        self.squareBtn.setIconSize(QtCore.QSize(50, 50))
        self.squareBtn.setCheckable(True)
        self.squareBtn.setObjectName("squareBtn")
        self.horizontalLayout_3.addWidget(self.squareBtn)
        self.circleBtn = QtWidgets.QPushButton(self.shadeFrame)
        self.circleBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.circleBtn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/vertexture/skin/vertexture/misc/circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.circleBtn.setIcon(icon5)
        self.circleBtn.setIconSize(QtCore.QSize(50, 50))
        self.circleBtn.setCheckable(True)
        self.circleBtn.setObjectName("circleBtn")
        self.horizontalLayout_3.addWidget(self.circleBtn)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        self.verticalLayout_8.addWidget(self.shadeFrame)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.glueBtn = QtWidgets.QPushButton(self.frame_4)
        self.glueBtn.setMinimumSize(QtCore.QSize(40, 25))
        self.glueBtn.setMaximumSize(QtCore.QSize(40, 25))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/vertexture/skin/vertexture/misc/magnet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.glueBtn.setIcon(icon6)
        self.glueBtn.setCheckable(True)
        self.glueBtn.setFlat(False)
        self.glueBtn.setObjectName("glueBtn")
        self.horizontalLayout_10.addWidget(self.glueBtn)
        self.lazyBtn = QtWidgets.QPushButton(self.frame_4)
        self.lazyBtn.setMinimumSize(QtCore.QSize(58, 25))
        self.lazyBtn.setCheckable(True)
        self.lazyBtn.setObjectName("lazyBtn")
        self.horizontalLayout_10.addWidget(self.lazyBtn)
        self.lazySpinStrength = QtWidgets.QSpinBox(self.frame_4)
        self.lazySpinStrength.setMinimumSize(QtCore.QSize(80, 23))
        self.lazySpinStrength.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lazySpinStrength.setWrapping(False)
        self.lazySpinStrength.setFrame(False)
        self.lazySpinStrength.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lazySpinStrength.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.lazySpinStrength.setAccelerated(True)
        self.lazySpinStrength.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.lazySpinStrength.setProperty("showGroupSeparator", False)
        self.lazySpinStrength.setMinimum(1)
        self.lazySpinStrength.setMaximum(10)
        self.lazySpinStrength.setProperty("value", 3)
        self.lazySpinStrength.setObjectName("lazySpinStrength")
        self.horizontalLayout_10.addWidget(self.lazySpinStrength)
        self.lazySpinDist = QtWidgets.QSpinBox(self.frame_4)
        self.lazySpinDist.setMinimumSize(QtCore.QSize(80, 23))
        self.lazySpinDist.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lazySpinDist.setWrapping(False)
        self.lazySpinDist.setFrame(False)
        self.lazySpinDist.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lazySpinDist.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.lazySpinDist.setAccelerated(True)
        self.lazySpinDist.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.lazySpinDist.setProperty("showGroupSeparator", False)
        self.lazySpinDist.setSuffix("")
        self.lazySpinDist.setMinimum(1)
        self.lazySpinDist.setMaximum(50)
        self.lazySpinDist.setProperty("value", 10)
        self.lazySpinDist.setObjectName("lazySpinDist")
        self.horizontalLayout_10.addWidget(self.lazySpinDist)
        self.horizontalLayout_10.setStretch(1, 1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.closeStrokeBtn = QtWidgets.QPushButton(self.frame_4)
        self.closeStrokeBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.closeStrokeBtn.setObjectName("closeStrokeBtn")
        self.verticalLayout_8.addWidget(self.closeStrokeBtn)
        self.verticalLayout_7.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.box4)
        self.line_9 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout.addWidget(self.line_9)
        self.box5 = ziCollapse(self.scrollAreaWidgetContents)
        self.box5.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.box5.setProperty("flat", True)
        self.box5.setObjectName("box5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.box5)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setHorizontalSpacing(0)
        self.gridLayout_7.setVerticalSpacing(1)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.symmetryBtn = QtWidgets.QPushButton(self.box5)
        self.symmetryBtn.setCheckable(True)
        self.symmetryBtn.setObjectName("symmetryBtn")
        self.gridLayout_7.addWidget(self.symmetryBtn, 1, 0, 1, 2)
        self.freezeSymBtn = QtWidgets.QPushButton(self.box5)
        self.freezeSymBtn.setMinimumSize(QtCore.QSize(0, 10))
        self.freezeSymBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.freezeSymBtn.setAutoFillBackground(False)
        self.freezeSymBtn.setCheckable(True)
        self.freezeSymBtn.setAutoDefault(False)
        self.freezeSymBtn.setDefault(False)
        self.freezeSymBtn.setFlat(False)
        self.freezeSymBtn.setObjectName("freezeSymBtn")
        self.gridLayout_7.addWidget(self.freezeSymBtn, 3, 0, 1, 2)
        self.verticalLayout_10.addLayout(self.gridLayout_7)
        self.verticalLayout.addWidget(self.box5)
        self.tapisserie = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.tapisserie.setMinimumSize(QtCore.QSize(0, 50))
        self.tapisserie.setAutoFillBackground(False)
        self.tapisserie.setStyleSheet("QFrame{\n"
"background-image: url(:/vertexture/skin/vertexture/tapisserie.png);\n"
"  opacity: 0.1;\n"
"}")
        self.tapisserie.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tapisserie.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tapisserie.setObjectName("tapisserie")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tapisserie)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.logLab = QtWidgets.QLabel(self.tapisserie)
        self.logLab.setEnabled(True)
        self.logLab.setStyleSheet("color: rgb(166, 166, 166);")
        self.logLab.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.logLab.setWordWrap(True)
        self.logLab.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.logLab.setObjectName("logLab")
        self.verticalLayout_12.addWidget(self.logLab)
        self.verticalLayout.addWidget(self.tapisserie)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setHorizontalSpacing(1)
        self.gridLayout_8.setVerticalSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.hotkeyBtn = QtWidgets.QPushButton(self.centralwidget)
        self.hotkeyBtn.setObjectName("hotkeyBtn")
        self.gridLayout_8.addWidget(self.hotkeyBtn, 0, 0, 1, 3)
        self.updateChk = QtWidgets.QPushButton(self.centralwidget)
        self.updateChk.setEnabled(True)
        self.updateChk.setObjectName("updateChk")
        self.gridLayout_8.addWidget(self.updateChk, 1, 0, 1, 3)
        self.hudChk = QtWidgets.QCheckBox(self.centralwidget)
        self.hudChk.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hudChk.setChecked(True)
        self.hudChk.setObjectName("hudChk")
        self.gridLayout_8.addWidget(self.hudChk, 5, 2, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_8.addWidget(self.line_5, 4, 0, 1, 3)
        self.hintsBtn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.hintsBtn.setFont(font)
        self.hintsBtn.setCheckable(True)
        self.hintsBtn.setObjectName("hintsBtn")
        self.gridLayout_8.addWidget(self.hintsBtn, 5, 0, 1, 1)
        self.helpBtn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.helpBtn.setFont(font)
        self.helpBtn.setCheckable(True)
        self.helpBtn.setDefault(False)
        self.helpBtn.setFlat(False)
        self.helpBtn.setObjectName("helpBtn")
        self.gridLayout_8.addWidget(self.helpBtn, 5, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_8)
        ziRailWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ziRailWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 316, 21))
        self.menubar.setObjectName("menubar")
        ziRailWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ziRailWindow)
        self.statusbar.setObjectName("statusbar")
        ziRailWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ziRailWindow)
        QtCore.QMetaObject.connectSlotsByName(ziRailWindow)

    def retranslateUi(self, ziRailWindow):
        ziRailWindow.setWindowTitle(QtWidgets.QApplication.translate("ziRailWindow", "MainWindow", None, -1))
        self.pickSrcBtn.setText(QtWidgets.QApplication.translate("ziRailWindow", "Set Source", None, -1))
        self.refBox.setText(QtWidgets.QApplication.translate("ziRailWindow", "As Reference", None, -1))
        self.box1.setProperty("title", QtWidgets.QApplication.translate("ziRailWindow", "SUBDIVISIONS", None, -1))
        self.lockedPinchChk.setText(QtWidgets.QApplication.translate("ziRailWindow", "Pinch", None, -1))
        self.slidBtn.setText(QtWidgets.QApplication.translate("ziRailWindow", "Reset", None, -1))
        self.uLabUp.setText(QtWidgets.QApplication.translate("ziRailWindow", "U ", None, -1))
        self.vLabUp.setText(QtWidgets.QApplication.translate("ziRailWindow", "V ", None, -1))
        self.uLabDn.setText(QtWidgets.QApplication.translate("ziRailWindow", ".", None, -1))
        self.vLabDn.setText(QtWidgets.QApplication.translate("ziRailWindow", ".", None, -1))
        self.displayProjBtn.setText(QtWidgets.QApplication.translate("ziRailWindow", "Proj. Distance", None, -1))
        self.bridg_lab.setText(QtWidgets.QApplication.translate("ziRailWindow", " Bridge Subs:", None, -1))
        self.reversBridgBtn.setText(QtWidgets.QApplication.translate("ziRailWindow", "Reverse", None, -1))
        self.tweakBtn.setText(QtWidgets.QApplication.translate("ziRailWindow", "Tweak Mode", None, -1))
        self.box2.setProperty("title", QtWidgets.QApplication.translate("ziRailWindow", "APPEARANCE", None, -1))
        self.viewportBtn.setText(QtWidgets.QApplication.translate("ziRailWindow", "SHADER VIEWPORT UI", None, -1))
        self.shaderApplyBtn.setText(QtWidgets.QApplication.translate("ziRailWindow", "Toggle", None, -1))
        self.box3.setProperty("title", QtWidgets.QApplication.translate("ziRailWindow", "BRUSH PROPERTIES", None, -1))
        self.moverad_lab.setText(QtWidgets.QApplication.translate("ziRailWindow", "Move Radius:", None, -1))
        self.relaxrad_lab.setText(QtWidgets.QApplication.translate("ziRailWindow", "Relax Radius:", None, -1))
        self.relaxint_lab.setText(QtWidgets.QApplication.translate("ziRailWindow", "Relax Intensity:", None, -1))
        self.relaxBrBtn.setText(QtWidgets.QApplication.translate("ziRailWindow", "Relax Brush", None, -1))
        self.moveBtn.setText(QtWidgets.QApplication.translate("ziRailWindow", "Move Brush", None, -1))
        self.freezeBBtn.setText(QtWidgets.QApplication.translate("ziRailWindow", "Freeze Brush", None, -1))
        self.backfBtn.setText(QtWidgets.QApplication.translate("ziRailWindow", "Brush On Backface", None, -1))
        self.freezeBtn.setText(QtWidgets.QApplication.translate("ziRailWindow", "Freeze Borders", None, -1))
        self.box4.setProperty("title", QtWidgets.QApplication.translate("ziRailWindow", "DRAWING", None, -1))
        self.ziRailLaunchBtn.setText(QtWidgets.QApplication.translate("ziRailWindow", "RAIL MODE", None, -1))
        self.quadBtn.setText(QtWidgets.QApplication.translate("ziRailWindow", "Toggle QUADDRAW MODE", None, -1))
        self.glueBtn.setText(QtWidgets.QApplication.translate("ziRailWindow", ".", None, -1))
        self.lazyBtn.setText(QtWidgets.QApplication.translate("ziRailWindow", "LazyMode", None, -1))
        self.lazySpinStrength.setPrefix(QtWidgets.QApplication.translate("ziRailWindow", "Strength: ", None, -1))
        self.lazySpinDist.setPrefix(QtWidgets.QApplication.translate("ziRailWindow", "Distance: ", None, -1))
        self.closeStrokeBtn.setText(QtWidgets.QApplication.translate("ziRailWindow", "Close Stroke(s)", None, -1))
        self.box5.setProperty("title", QtWidgets.QApplication.translate("ziRailWindow", "SYMMETRY", None, -1))
        self.symmetryBtn.setText(QtWidgets.QApplication.translate("ziRailWindow", "Symmetry", None, -1))
        self.freezeSymBtn.setText(QtWidgets.QApplication.translate("ziRailWindow", "Freeze Median Axis", None, -1))
        self.logLab.setText(QtWidgets.QApplication.translate("ziRailWindow", "...", None, -1))
        self.hotkeyBtn.setText(QtWidgets.QApplication.translate("ziRailWindow", "Hotkeys", None, -1))
        self.updateChk.setText(QtWidgets.QApplication.translate("ziRailWindow", "Check Update", None, -1))
        self.hudChk.setText(QtWidgets.QApplication.translate("ziRailWindow", " HUD Display", None, -1))
        self.hintsBtn.setText(QtWidgets.QApplication.translate("ziRailWindow", "Disable Hotkeys", None, -1))
        self.helpBtn.setText(QtWidgets.QApplication.translate("ziRailWindow", "Disable Help", None, -1))

from zi_Widget.zi_Windows import ziCollapse
from . import ziRessources_rc

# -- Vtx python version 3
